name = "Synth"
uuid = "17321cac-a4bc-4530-aa11-a8f457f422f2"
version = "0.2.0"
authors = ["Srikumar K. S. <srikumar.subramanian@krea.edu.in>"]

[deps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Gtk4 = "9db2cae5-386f-4011-9d63-a5602296539b"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
LibSndFile = "b13ce0c6-77b0-50c6-a2db-140568b8d1a5"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
PortAudio = "80ea8bcb-4634-5cb3-8ee8-a132660d1d2d"
PortMidi = "42b16160-194f-40b3-8419-7a13c10fa643"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SampledSignals = "bd7594eb-a658-542f-9e75-4c4d8908c167"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
ThreadPools = "b189fb0b-2eb5-4ed4-bc0c-d34c51242431"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"

[compat]
Cairo = "1.1.1"
DSP = "0.7.10"
FileIO = "1.16.6"
Gtk4 = "0.7.10"
Interact = "0.10.5"
LibSndFile = "2.4.0"
Observables = "0.5.5"
PortAudio = "1.3.0"
PortMidi = "0.1.0"
Printf = "1.11.0"
Random = "1.11.0"
SampledSignals = "2.1.4"
StaticArrays = "1.9.15"
ThreadPools = "2.1.1"
URIs = "1.6.1"
julia = "1.11.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
